### ISSUE TITLE
Website Cohesion

### ISSUE THREAD

**Issue by Tantrabobus** [DTI22/Fuzz-Foam#1]
I'd like permission from the team to make changes to other team members' code to help make a more cohesive website. 

Some of the things I've noticed so far that need to be remedied: 
- lack of header/nav bar on several pages
- nonfunctioning navbar links that do not redirect to appropriate pages 

I'm not interested in altering anyone's content (e.g. photos, videos, text), I'm just willing to do the work to make our website a more cohesive whole (per the final project minimum requirements).

If you're okay with me making these changes to your code please let me know either here or in the Teams chat.

**UPDATE 01/11/2023:**

Added style for livestream and profile (based on Parker's) to home.css. Most style is globalized if authors utilize home.css -- avoided modifying or consolidating css files other than home.css.

Should make it easier for other authors to create profile pages, or I could create profile pages for all authors that could then be modified.

~~"Service" page remains non-existant? Should we consider removing it from global navbar?~~ 
@bmehrhof will be updating soon

**UPDATE 01/12/2023**

Fixed missing "Cat Rescue" link on home page.

**UPDATE 01/13/2023**

Identified and fixed a problem that was causing our GitHub Page from not displaying (home.html changed to index.html to be an entry file per the GitHub instructions [here](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site)) -- keeping index and home.html files both to allow for easier testing and implementation.

GitHub Page can be accessed here: https://dti22.github.io/Fuzz-Foam/

(Please note that changes to code may not be reflected on the site for 10 minutes to an hour and will yield a 404 error until the changes take effect)

**IMPORTANT!!**

Page and image links MUST have /Fuzz-Foam/ before the html or _local_  image file location (in /images/) in order to work properly on our [GitHub Page](https://dti22.github.io/Fuzz-Foam/) (how we "hand-in" our Final Project). 

If you still need/want to use the "Go Live" Virtual Studio Code extension you will have to remove the /Fuzz-Foam/ from links in order for your links or images to work/display properly.

If you find this confusing or have any questions feel free to ask.

**Comment by pseesangrit** [comment]
Yes. I am okay with that.

**Comment by bmehrhof** [comment]
Yeah I’m ok with that as well!

**Comment by leemcpeters** [comment]
As long as the team is okay with it, I am okay with it as well.

**Comment by Tantrabobus** [comment]
added update to top post

**Comment by lovelylady75** [comment]
Sounds good to me

**Comment by bmehrhof** [comment]
I am currently working on the services page I apologize for not having submitted my work yet I am adding css to my page to match the stylings on the other pages! Will let the team know when I have submitted my work

**Comment by Tantrabobus** [comment]
> I am currently working on the services page I apologize for not having submitted my work yet I am adding css to my page to match the stylings on the other pages! Will let the team know when I have submitted my work

Awesome! Updated top post to reflect 😃

**Comment by Tantrabobus** [comment]
Fixed missing "Cat Rescue" navbar link on home page

**Comment by Tantrabobus** [comment]
Please review the most recent updates, fixes, and notes in the top post. Thanks!

**Comment by Tantrabobus** [comment]
We passed!
